services:
    app:
        build:
            context: .
            dockerfile: ../.docker/php/Dockerfile
            args:
                user: laravel
                uid: 1000
        image: waverewards-app
        container_name: waverewards-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - waverewards-network

    # 2. O Servidor Web (Nginx) - Porta 8000
    nginx:
        image: nginx:alpine
        container_name: waverewards-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - waverewards-network

    db:
        image: mariadb:10.11
        container_name: waverewards-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3310:3306"
        networks:
            - waverewards-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: waverewards-pma
        links:
            - db:db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: waverewards-db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - waverewards-network

    redis:
        image: redis:alpine
        container_name: waverewards-redis
        networks:
            - waverewards-network

    queue:
        build:
            context: .
            dockerfile: ../.docker/php/Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: waverewards-queue
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: "php artisan queue:work --tries=3 --timeout=90"
        depends_on:
            - app
            - db
            - redis
        networks:
            - waverewards-network

    vite:
        build:
            context: .
            dockerfile: ../.docker/php/Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: waverewards-vite
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "5173:5173"
        command: "npm run dev -- --host"
        networks:
            - waverewards-network

networks:
    waverewards-network:
        driver: bridge

volumes:
    dbdata: